### ISSUE TITLE
how to send message to friends using skype4py

### ISSUE THREAD

**Issue by wdfsinap** [Skype4Py/Skype4Py#48]
seems sending message not working. can you show some examples?

**Comment by amazpyel** [comment]
Hi @wdfsinap , 

Here is an example:

```python
import Skype4Py
import sys

skype = Skype4Py.Skype()
skype.Attach()
user = sys.argv[1]
message = ' '.join(sys.argv[2:])
skype.SendMessage(user, message)
```

You may run it in the following way from command line:

```python script.py username message```

**Comment by davsebamse** [comment]
Thanks for your example. I have included it in the readme.

**Comment by lavinachitara** [comment]
Hi,

In windows 
skype.SendMessage(user.fullname, 'May I help you')

above function is not working and throwing an error as below:

raise SkypeError(int(errnum), errstr)
Skype4Py.errors.SkypeError: [Errno 508] CHAT: CREATE: opening a dialog to the given user failed

**Comment by hardiksanchawat** [comment]
Hi,

In Windows 10, I am trying to send message through above code. But I am getting following error.

Exception in thread Skype4Py API thread:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Program Files\Anaconda2\lib\site-packages\Skype4Py\api\windows.py", line 92, in run
    if not self.create_window():
  File "C:\Program Files\Anaconda2\lib\site-packages\Skype4Py\api\windows.py", line 242, in create_window
    wclass = windll.user32.RegisterClassA(byref(self.window_class))
WindowsError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

Could you please let me know, what is the root cause and how would I resolve?

Thanks in Advance!
